### ISSUE TITLE
Binary linux 32 bit X86 please

### ISSUE THREAD

**Issue by surereddy** [messyidea/sufttun#1]
hello sir can u please give me Binary for linux 32 bit X86 server

**Comment by messyidea** [comment]
You can go to the [release](https://github.com/messyidea/sufttun/releases) page to download the binary.
But I recommend you to use [kcptun](https://github.com/xtaci/kcptun) instead. Because the upsteam project suft have not updated for a long time.

**Comment by surereddy** [comment]
Thank you sir.Any plans to upgrade to new version please
