### ISSUE TITLE
portd应该为porta吧？

### ISSUE THREAD

**Issue by luckypoem** [messyidea/sufttun#2]
hi。
你的sample 里的这行：
client -l ":portc" -r "server:portd" -b 10 --key "yourkey" --tuncrypt true ，
portd应该为porta吧？即跟服务器端的 server所监听的端口一致。

**Comment by messyidea** [comment]
嗯，是的。

**Comment by luckypoem** [comment]
在vps上，运行go get github.com/messyidea/sufttun/server遇错，怎么解决？
root@ar:~/go/gopath# go get github.com/messyidea/sufttun/server
# github.com/messyidea/sufttun/server
github.com/spance/suft/protocol.net_pollSetDeadline: relocation target net.runtime_pollSetDeadline not defined
github.com/spance/suft/protocol.net_pollSetDeadline: undefined: "net.runtime_pollSetDeadline"
root@ar:~/go/gopath#

在mac上，运行go get github.com/messyidea/sufttun/client倒是未遇错

**Comment by messyidea** [comment]
上游已经不维护了，golang最新版编译不成功
还是用kcptun吧

**Comment by luckypoem** [comment]
我在linux vps上装了go1.10,然后又装了go1.8,不过2者有点“打架”，linux vps上有什么go版本管理器吗？

**Comment by luckypoem** [comment]
看到了https://github.com/moovweb/gvm

**Comment by messyidea** [comment]
恩，不过我觉得 golang 没啥必要装老版，除非遇到应用真正不兼容的情况。
