### ISSUE TITLE
something is wrong 

### ISSUE THREAD

**Issue by surereddy** [messyidea/sufttun#4]
Hello sir i tried to run the software but i have a small problem here is log below

sufttun-server sufttun-server -l ":12050" -t "127.0.0.1:40000" -b 10 --key "yourkey" --tuncrypt true

2018/02/12 14:02:48 listening on  :29900
2018/02/12 14:02:48 tunnel encryption: false

as per my config local port on server should 12050 but it shows as 29900 which is the default

**Comment by surereddy** [comment]
2018/02/12 14:08:39 rtt 437
2018/02/12 14:08:39 connected from 196.150.33.213:3333
2018/02/12 14:09:09 [ERR] yamux: Invalid protocol version: 194
2018/02/12 14:09:09 invalid protocol version
2018/02/12 14:09:09 shutdown 0\



2018/02/12 16:14:53 listening on: [::]:12948
2018/02/12 16:14:53 rtt 256
2018/02/12 16:14:53 connected to 45.77.213.216:29900
2018/02/12 16:14:53 tunnel encryption: true
2018/02/12 16:15:23 [ERR] yamux: keepalive failed: session shutdown
2018/02/12 16:15:23 shutdown 0

**Comment by surereddy** [comment]
2018/02/12 14:15:17 connected from 196.150.33.213:12948
2018/02/12 14:15:47 [ERR] yamux: Invalid protocol version: 127
2018/02/12 14:15:47 invalid protocol version
2018/02/12 14:15:48 shutdown 0

**Comment by messyidea** [comment]
I have seen that you have an extra word `sufttun-server` on your command. It's the result that cause this problem.
The right command is:
```
sufttun-server -l ":12050" -t "127.0.0.1:40000" -b 10 --key "yourkey" --tuncrypt true
```

**Comment by surereddy** [comment]
Hello sir thanks for guiding me to correct configuration of server and client .I have a question 

sufttun-server -l ":1205" -t "127.0.0.1:40000" -b 100 --key "yourkey" --tuncrypt true
sufttun-client -l ":3333" -r "server:1205" -b 10 --key "yourkey" --tuncrypt true &

From server side 
lsof -i:1205
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
sufttun-s 30842 root    3u  IPv6 609433      0t0  UDP *:1205

from Client Side
lsof -i:3333
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
sufttun-c 21925 root    3u  IPv6  46450      0t0  TCP *:3333 (LISTEN)
sufttun-c 21925 root    5u  IPv6  46451      0t0  UDP *:3333

in client side UDP and TCP are open on port 3333 .When i use UDP traffic to server i cannot get udp but when i use TCP i can see its working.Sir my question is there is no UDP on client side ? if udp is there i'm doing something wrong config ? Kindly check and update how can i get it working on udp 
thanks again sir.

**Comment by surereddy** [comment]
Sorry for the above message i'm really sorry i have checked the readme i found this 

client <--> suft-client  <--> suft-server  <--> server
    tcp <-> udp                        udp <-> tcp

Is it possible to have UDP in both direction ?
client <--> suft-client  <--> suft-server  <--> server
    udp<-> udp                        udp <-> udp

**Comment by messyidea** [comment]
Currently it do not support udp.

**Comment by surereddy** [comment]
Hello sir thank you for the message i have a problem while trying to run the software  once communication from server is down Client stops working it doesn't try to send messages to server till it gets connection back.IS there any way i can have the connection back to client once server is UP.Send timeout might corrupt outgoing messages 

my config from client 

sufttun-client -l ":3333" -r "95.201.30.XX:1205" -b 10 --key "yourkey" --tuncrypt true &
sh-4.3# 2018/02/16 20:51:44 listening on: [::]:3333
2018/02/16 20:51:45 rtt 97
2018/02/16 20:51:45 connected to 95.201.30.XX:1205
2018/02/16 20:51:45 tunnel encryption: true
2018/02/16 20:51:46 stream opened


lsof -i:3333
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
sufttun-c 598 root    3u  IPv6 692012      0t0  TCP *:3333 (LISTEN)
sufttun-c 598 root    5u  IPv6 692013      0t0  UDP *:3333 


server side

COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
sufttun-s 1578 root    3u  IPv6  15104      0t0  UDP *:1205

Once i do reboot on server .Once the server is back online .Client cannot connect to server automatically .Below are the message

sh-4.3# 2018/02/16 21:02:01 listening on: [::]:3333
2018/02/16 21:02:01 rtt 94
2018/02/16 21:02:01 connected to 95.201.30.XX:1205
2018/02/16 21:02:01 tunnel encryption: true
2018/02/16 21:02:08 stream opened
2018/02/16 21:02:27 shutdown 0
2018/02/16 21:02:27 stream closed
2018/02/16 21:02:40 session shutdown
2018/02/16 21:02:40 listen udp :3333: bind: address already in use
